export const UPDATE_TEMPERATURE = 'UPDATE_TEMPERATURE';

export const ADD_PRODUCT_TO_FREEZER = 'ADD_PRODUCT_TO_FREEZER';

export const REMOVE_SCOOP = 'REMOVE_SCOOP';

export const DEDUCT_STOCK = 'DEDUCT_STOCK';
